#!/bin/sh

EXT=".php"
PATHNAME=$(readlink $0)
if [ $? -ne 0 ] ; then
	DIRNAME=$(dirname $0)
else
	DIRNAME=$(dirname $PATHNAME)
fi

if [ `whoami` != "root" ]
then
    # echo "Performing sudo - I need root to edit your hosts file."
    # The above message is included if anyone wants it, but it got annoying.
    sudo $0 $*
    exit $?
fi

$DIRNAME/get-shit-done$EXT $*
